# Generated by Django 5.1.4 on 2026-06-27 11:22

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('generated_pdf', 'PDF i gjeneruar'), ('signed_pdf', 'PDF i firmosur'), ('attachment', 'Shtojcë')], max_length=20)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='forms.form')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_documentfile',
                'ordering': ['-created_at'],
            },
        ),
    ]
