/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpbRouteImport } from './routes/opb'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AutoritetetRouteImport } from './routes/autoritetet'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsIndexRouteImport } from './routes/forms.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FormulareNewRouteImport } from './routes/formulare.new'
import { Route as FormulareIdRouteImport } from './routes/formulare.$id'
import { Route as FormsNewRouteImport } from './routes/forms.new'
import { Route as FormsIdRouteImport } from './routes/forms.$id'
import { Route as DocPrintIdRouteImport } from './routes/doc-print.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminInstitutionsRouteImport } from './routes/admin.institutions'

const OpbRoute = OpbRouteImport.update({
  id: '/opb',
  path: '/opb',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoritetetRoute = AutoritetetRouteImport.update({
  id: '/autoritetet',
  path: '/autoritetet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FormulareNewRoute = FormulareNewRouteImport.update({
  id: '/formulare/new',
  path: '/formulare/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulareIdRoute = FormulareIdRouteImport.update({
  id: '/formulare/$id',
  path: '/formulare/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsNewRoute = FormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIdRoute = FormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocPrintIdRoute = DocPrintIdRouteImport.update({
  id: '/doc-print/$id',
  path: '/doc-print/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstitutionsRoute = AdminInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/autoritetet': typeof AutoritetetRoute
  '/login': typeof LoginRoute
  '/opb': typeof OpbRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/doc-print/$id': typeof DocPrintIdRoute
  '/forms/$id': typeof FormsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/formulare/$id': typeof FormulareIdRoute
  '/formulare/new': typeof FormulareNewRoute
  '/admin/': typeof AdminIndexRoute
  '/forms/': typeof FormsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autoritetet': typeof AutoritetetRoute
  '/login': typeof LoginRoute
  '/opb': typeof OpbRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/doc-print/$id': typeof DocPrintIdRoute
  '/forms/$id': typeof FormsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/formulare/$id': typeof FormulareIdRoute
  '/formulare/new': typeof FormulareNewRoute
  '/admin': typeof AdminIndexRoute
  '/forms': typeof FormsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/autoritetet': typeof AutoritetetRoute
  '/login': typeof LoginRoute
  '/opb': typeof OpbRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/doc-print/$id': typeof DocPrintIdRoute
  '/forms/$id': typeof FormsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/formulare/$id': typeof FormulareIdRoute
  '/formulare/new': typeof FormulareNewRoute
  '/admin/': typeof AdminIndexRoute
  '/forms/': typeof FormsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/autoritetet'
    | '/login'
    | '/opb'
    | '/admin/institutions'
    | '/admin/system'
    | '/admin/users'
    | '/doc-print/$id'
    | '/forms/$id'
    | '/forms/new'
    | '/formulare/$id'
    | '/formulare/new'
    | '/admin/'
    | '/forms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autoritetet'
    | '/login'
    | '/opb'
    | '/admin/institutions'
    | '/admin/system'
    | '/admin/users'
    | '/doc-print/$id'
    | '/forms/$id'
    | '/forms/new'
    | '/formulare/$id'
    | '/formulare/new'
    | '/admin'
    | '/forms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/autoritetet'
    | '/login'
    | '/opb'
    | '/admin/institutions'
    | '/admin/system'
    | '/admin/users'
    | '/doc-print/$id'
    | '/forms/$id'
    | '/forms/new'
    | '/formulare/$id'
    | '/formulare/new'
    | '/admin/'
    | '/forms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AutoritetetRoute: typeof AutoritetetRoute
  LoginRoute: typeof LoginRoute
  OpbRoute: typeof OpbRoute
  DocPrintIdRoute: typeof DocPrintIdRoute
  FormsIdRoute: typeof FormsIdRoute
  FormsNewRoute: typeof FormsNewRoute
  FormulareIdRoute: typeof FormulareIdRoute
  FormulareNewRoute: typeof FormulareNewRoute
  FormsIndexRoute: typeof FormsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/opb': {
      id: '/opb'
      path: '/opb'
      fullPath: '/opb'
      preLoaderRoute: typeof OpbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoritetet': {
      id: '/autoritetet'
      path: '/autoritetet'
      fullPath: '/autoritetet'
      preLoaderRoute: typeof AutoritetetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/': {
      id: '/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/formulare/new': {
      id: '/formulare/new'
      path: '/formulare/new'
      fullPath: '/formulare/new'
      preLoaderRoute: typeof FormulareNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulare/$id': {
      id: '/formulare/$id'
      path: '/formulare/$id'
      fullPath: '/formulare/$id'
      preLoaderRoute: typeof FormulareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/new': {
      id: '/forms/new'
      path: '/forms/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof FormsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$id': {
      id: '/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof FormsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc-print/$id': {
      id: '/doc-print/$id'
      path: '/doc-print/$id'
      fullPath: '/doc-print/$id'
      preLoaderRoute: typeof DocPrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/institutions': {
      id: '/admin/institutions'
      path: '/institutions'
      fullPath: '/admin/institutions'
      preLoaderRoute: typeof AdminInstitutionsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInstitutionsRoute: typeof AdminInstitutionsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInstitutionsRoute: AdminInstitutionsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AutoritetetRoute: AutoritetetRoute,
  LoginRoute: LoginRoute,
  OpbRoute: OpbRoute,
  DocPrintIdRoute: DocPrintIdRoute,
  FormsIdRoute: FormsIdRoute,
  FormsNewRoute: FormsNewRoute,
  FormulareIdRoute: FormulareIdRoute,
  FormulareNewRoute: FormulareNewRoute,
  FormsIndexRoute: FormsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
